/* Generated by tools/emit-plugin.mjs — do not edit by hand. */
/* build 18e9cf65b8d0 */
/* Preset anchors come from presets.json; the color math below is tools/lib/ramp.mjs
   and tools/lib/ladder.mjs inlined verbatim, so runtime recomputation and the
   shipped presets share one implementation. */
window.__ModuleLoader__.load({
	id: "@barneyzhaoooo/dsh-theme-codex",
	factory: (require) => {
		const React = require('react')
		const h = React.createElement

		const PACKAGE = "@barneyzhaoooo/dsh-theme-codex"
		const KEY_ENABLED = 'codex-theme:enabled'
		const KEY_PRESET = 'codex-theme:preset'
		const KEY_FONT = 'codex-theme:font'
		const KEY_UI_FONT = 'codex-theme:ui-font'
		const KEY_CUSTOM = {
			accent: 'codex-theme:accent',
			lightBg: 'codex-theme:light-bg',
			lightFg: 'codex-theme:light-fg',
			darkBg: 'codex-theme:dark-bg',
			darkFg: 'codex-theme:dark-fg',
		}
		const EVENT = 'codex-theme:changed'
		const DEFAULT_PRESET = "flexoki"

		// >>> inlined:ramp+ladder
		// tools/lib/ramp.mjs + tools/lib/ladder.mjs, with the export keyword stripped
		/**
		 * Shared color math and ramp construction for the DSH theme presets.
		 *
		 * DSH's token model is a two-layer indirection: ~99 `--dsw-alias-*` semantic
		 * tokens all reference stops of ~77 `--dsw-static-*` palettes, and those static
		 * palettes hold the SAME value in light and dark. The modes differ only in which
		 * stop each alias reads. So a re-skin means re-laying the static ramps, and the
		 * alias layer — hover, active, border and elevation derivations included —
		 * follows for free.
		 *
		 * Ramps are interpolated in Oklab. Stop numbers are treated as a lightness
		 * scale (t = stop / 1000), which is how both DSH's stops and Flexoki's base
		 * scale are laid out.
		 */

		// ---------------------------------------------------------------- color math

		const srgbToLinear = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)
		const linearToSrgb = (c) => (c <= 0.0031308 ? c * 12.92 : 1.055 * c ** (1 / 2.4) - 0.055)

		function hexToRgb(hex) {
		  if (typeof hex !== 'string') throw new TypeError(`expected a hex color, got ${JSON.stringify(hex)}`)
		  let h = hex.replace('#', '')
		  if (h.length === 3) h = h.split('').map((c) => c + c).join('')
		  // 8-digit forms carry alpha; the ramp math works on the opaque triple.
		  if (h.length === 8) h = h.slice(0, 6)
		  if (!/^[0-9a-fA-F]{6}$/.test(h)) throw new TypeError(`not a hex color: ${hex}`)
		  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255)
		}

		const rgbToHex = (rgb) =>
		  '#' + rgb.map((c) => Math.round(Math.min(1, Math.max(0, c)) * 255).toString(16).padStart(2, '0')).join('')

		function rgbToOklab([r, g, b]) {
		  const [R, G, B] = [r, g, b].map(srgbToLinear)
		  const l = Math.cbrt(0.4122214708 * R + 0.5363325363 * G + 0.0514459929 * B)
		  const m = Math.cbrt(0.2119034982 * R + 0.6806995451 * G + 0.1073969566 * B)
		  const s = Math.cbrt(0.0883024619 * R + 0.2817188376 * G + 0.6299787005 * B)
		  return [
		    0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
		    1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
		    0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s,
		  ]
		}

		function oklabToRgb([L, a, bb]) {
		  const l = (L + 0.3963377774 * a + 0.2158037573 * bb) ** 3
		  const m = (L - 0.1055613458 * a - 0.0638541728 * bb) ** 3
		  const s = (L - 0.0894841775 * a - 1.291485548 * bb) ** 3
		  return [
		    linearToSrgb(4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s),
		    linearToSrgb(-1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s),
		    linearToSrgb(-0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s),
		  ]
		}

		const lerp = (a, b, t) => a + (b - a) * t

		/** Interpolate two hex colors in Oklab. */
		function mix(from, to, t) {
		  const A = rgbToOklab(hexToRgb(from))
		  const B = rgbToOklab(hexToRgb(to))
		  return rgbToHex(oklabToRgb([0, 1, 2].map((i) => lerp(A[i], B[i], t))))
		}

		function luminance(hex) {
		  const [r, g, b] = hexToRgb(hex).map(srgbToLinear)
		  return 0.2126 * r + 0.7152 * g + 0.0722 * b
		}

		/** WCAG contrast ratio. */
		function contrast(a, b) {
		  const [x, y] = [luminance(a), luminance(b)].sort((p, q) => q - p)
		  return (x + 0.05) / (y + 0.05)
		}

		/** `a12` -> 12% -> the two-digit alpha suffix DSH writes (`1f`). */
		const alphaSuffix = (pct) => Math.round((pct / 100) * 255).toString(16).padStart(2, '0')

		/**
		 * Lift `start` toward `toward` until it reaches `targetContrast` against
		 * `surface`, or return it unchanged when it already does.
		 *
		 * Mixing toward the foreground raises contrast monotonically, so a bisection is
		 * exact. This is a floor, never a ceiling: a stop that already clears the target
		 * is returned untouched, which is what keeps an already-verified preset stable.
		 */
		function raiseToContrast(start, toward, surface, targetContrast) {
		  if (contrast(start, surface) >= targetContrast) return start
		  let lo = 0
		  let hi = 1
		  for (let i = 0; i < 24; i += 1) {
		    const mid = (lo + hi) / 2
		    if (contrast(mix(start, toward, mid), surface) >= targetContrast) hi = mid
		    else lo = mid
		  }
		  return mix(start, toward, hi)
		}

		// ---------------------------------------------------------------- ramps

		/**
		 * Build a ramp by interpolating through pinned knots.
		 *
		 * @param stops  stop numbers that exist for this family
		 * @param knots  [stop, color] pins, sorted ascending; must span 0..1000
		 */
		function buildRamp(stops, knots) {
		  const sorted = [...knots].sort((a, b) => a[0] - b[0])
		  for (let i = 1; i < sorted.length; i += 1) {
		    if (sorted[i][0] === sorted[i - 1][0]) throw new Error(`duplicate ramp knot at stop ${sorted[i][0]}`)
		  }
		  const value = (stop) => {
		    if (stop <= sorted[0][0]) return sorted[0][1]
		    for (let i = 0; i < sorted.length - 1; i += 1) {
		      const [s0, c0] = sorted[i]
		      const [s1, c1] = sorted[i + 1]
		      if (stop >= s0 && stop <= s1) return mix(c0, c1, (stop - s0) / (s1 - s0))
		    }
		    return sorted[sorted.length - 1][1]
		  }
		  return Object.fromEntries(stops.map((s) => [s, value(s)]))
		}

		// ---------------------------------------------------------------- theme files

		/**
		 * Read a Ghostty-format theme (what Prowl ships 463 of).
		 *
		 * Each file is self-consistent for its own mode: the light file's palette is
		 * tuned for a light background and the dark file's for a dark one, so preset
		 * generation reads the matching file per mode rather than transforming one.
		 */
		function parseGhosttyTheme(text, label = 'theme') {
		  const out = { palette: {}, bg: null, fg: null }
		  for (const line of text.split('\n')) {
		    const m = /^\s*(palette|background|foreground)\s*=\s*(?:(\d+)=)?(#?[0-9a-fA-F]+)\s*$/.exec(line)
		    if (!m) continue
		    if (m[1] === 'palette') out.palette[Number(m[2])] = m[3]
		    else if (m[1] === 'background') out.bg = m[3]
		    else out.fg = m[3]
		  }
		  if (!out.bg || !out.fg) throw new Error(`${label}: no background/foreground line found`)
		  return out
		}

		/** Ghostty ANSI indices used as preset sources. */
		const ANSI = { red: 1, green: 2, yellow: 3, blue: 4, cyan: 6, magenta: 5 }

		// ---------------------------------------------------------------- semantic families

		/**
		 * Lay one semantic family's stops from a single base color per mode.
		 *
		 * Tints below the base stop ease toward the mode's surface; shades above it ease
		 * toward near-black. The exponents are what keep the lightest stops close to the
		 * background, which is how DSH's own ramps (and Tailwind's) are shaped.
		 *
		 * @param stops     stop labels present for this family, e.g. ['50','100','400-a12']
		 * @param baseLight base color in light mode
		 * @param baseDark  base color in dark mode
		 * @param surfaceLight / surfaceDark  the mode's background, the tint target
		 * @param baseStop  the stop treated as "the color itself"
		 */
		function buildFamily(stops, baseLight, baseDark, surfaceLight, surfaceDark, baseStop = 500) {
		  const numbers = stops.map((s) => Number.parseInt(s, 10)).filter(Number.isFinite)
		  const low = Math.min(...numbers)
		  const high = Math.max(...numbers)

		  const one = (stop, base, surface) => {
		    if (stop === baseStop) return base
		    if (stop < baseStop) {
		      const t = (baseStop - stop) / (baseStop - low || 1)
		      return mix(base, surface, 1 - (1 - t) ** 1.5)
		    }
		    const t = (stop - baseStop) / (high - baseStop || 1)
		    return mix(base, '#000000', 0.88 * t ** 1.2)
		  }

		  const perStop = (label) => {
		    const num = Number.parseInt(label, 10)
		    if (!Number.isFinite(num)) throw new Error(`stop label ${label} has no leading number`)
		    return { light: one(num, baseLight, surfaceLight), dark: one(num, baseDark, surfaceDark) }
		  }

		  const out = {}
		  for (const label of stops) {
		    // `-aNN` alpha variants reuse their base stop's color and re-attach alpha.
		    const alpha = /-a(\d+)$/.exec(label)
		    if (alpha) {
		      const baseLabel = label.replace(/-a\d+$/, '')
		      const base = perStop(baseLabel)
		      const suffix = alphaSuffix(Number(alpha[1]))
		      out[label] = { light: base.light + suffix, dark: base.dark + suffix }
		      continue
		    }
		    out[label] = perStop(label)
		  }
		  return out
		}

		/**
		 * The token ladder: DSH's stop inventory and the one function that turns source
		 * anchors into the full `--dsw-static-*` payload.
		 *
		 * This module is shared verbatim between the build tools and the browser: the
		 * bundle generator strips the `export ` keywords and inlines it, so a custom
		 * color recomputed at runtime goes through exactly the code that produced the
		 * shipped presets. If the two ever diverged, tools/verify-runtime.mjs fails.
		 *
		 * A preset is therefore stored as its SOURCE ANCHORS (background, foreground and
		 * one base color per semantic family), not as a frozen token table — the table
		 * is a derived value that any background/foreground/accent edit can regenerate.
		 */

		/**
		 * Stop labels exactly as DSH declares them in its own stylesheets.
		 * tools/build-presets.mjs asserts these against baseline-palette.json, so a DSH
		 * upgrade that adds or removes a stop fails the build instead of silently
		 * shipping a partially-covered theme.
		 */
		const FAMILY_STOPS = {
		  'neutral-bluish': ['00', '50', '60', '75', '100', '150', '200', '300', '400', '500', '600', '700', '750', '800', '850', '875', '900', '950', '1000'],
		  neutral: ['00', '50', '100', '150', '200', '250', '300', '400', '500', '550', '600', '700', '800', '850', '900', '1000'],
		  red: ['50', '100', '400', '400-a12', '500', '600', '600-a08', '900'],
		  green: ['100', '400', '500', '500-a08', '500-a12', '900'],
		  amber: ['100', '400', '500', '600', '900'],
		  blue: ['50', '50p', '75', '100', '300', '400', '450', '500', '600', '800', '900', '950'],
		  deepseek: ['50', '100', '200', '300', '400', '450', '500', '600', '700-delete', '800', '900'],
		}

		const NEUTRAL_BLUISH_STOPS = FAMILY_STOPS['neutral-bluish'].map(Number)
		const PLAIN_NEUTRAL_STOPS = FAMILY_STOPS.neutral.map(Number)

		/** Families whose base color comes from the theme's ANSI palette. */
		const SEMANTIC_FAMILIES = ['red', 'green', 'amber', 'blue']

		/** The accent family is separate: it is the user-facing 强调色 control. */
		const ACCENT_FAMILY = 'deepseek'

		/**
		 * Contrast floors for the text ladder.
		 *
		 * Presets inherit their theme's contrast budget, and several themes ship a soft
		 * foreground, which pushed secondary/tertiary text below what DSH's own defaults
		 * deliver. The ladder is therefore floored at WCAG AA body text (4.5) for the
		 * secondary tier and at the large-text/graphic tier (3.0) for tertiary, clamped
		 * by the theme's own budget so a low-contrast theme degrades proportionally
		 * instead of becoming unreachable.
		 */
		const SECONDARY_FLOOR = 4.5
		const TERTIARY_FLOOR = 3.0

		const STATIC = (family, label) => `--dsw-static-${family}-${label}`

		/** Build the two neutral ramps for a background/foreground pair. */
		function neutralRamps(lightBg, lightFg, darkBg, darkFg, paper) {
		  const bluishLight = buildRamp(NEUTRAL_BLUISH_STOPS, [
		    [0, lightBg],
		    [200, mix(lightBg, lightFg, 0.18)],
		    [500, mix(lightBg, lightFg, 0.5)],
		    [700, mix(lightBg, lightFg, 0.72)],
		    [1000, lightFg],
		  ])
		  // Dark aliases read stop 50 as primary text and 950 as the base background,
		  // so the ramp has to pass through both rather than run end to end.
		  const bluishDark = buildRamp(NEUTRAL_BLUISH_STOPS, [
		    [0, paper],
		    [50, darkFg],
		    [500, mix(darkFg, darkBg, 0.5)],
		    [800, mix(darkFg, darkBg, 0.82)],
		    [950, darkBg],
		    [1000, '#000000'],
		  ])

		  for (const [ramp, bg, fg, secondaryStop, tertiaryStop, primaryStop] of [
		    [bluishLight, lightBg, lightFg, 700, 600, 1000],
		    [bluishDark, darkBg, darkFg, 300, 400, 50],
		  ]) {
		    const budget = contrast(ramp[primaryStop], bg)
		    ramp[secondaryStop] = raiseToContrast(ramp[secondaryStop], fg, bg, Math.min(SECONDARY_FLOOR, budget * 0.95))
		    ramp[tertiaryStop] = raiseToContrast(ramp[tertiaryStop], fg, bg, Math.min(TERTIARY_FLOOR, budget * 0.65))
		  }

		  const plainLight = buildRamp(PLAIN_NEUTRAL_STOPS, [
		    [0, mix(lightBg, '#ffffff', 0.35)],
		    [500, mix(lightBg, lightFg, 0.5)],
		    [1000, mix(lightFg, '#000000', 0.15)],
		  ])
		  const plainDark = buildRamp(PLAIN_NEUTRAL_STOPS, [
		    [0, paper],
		    [50, darkFg],
		    [500, mix(darkFg, darkBg, 0.5)],
		    [950, darkBg],
		    [1000, '#000000'],
		  ])

		  return { bluish: { light: bluishLight, dark: bluishDark }, plain: { light: plainLight, dark: plainDark } }
		}

		/**
		 * Turn a preset's source anchors into its complete token payload.
		 *
		 * @param sources see the shape written by tools/build-presets.mjs: raw colors
		 *                only, never derived tokens.
		 */
		function buildTokens(sources) {
		  const { lightBg, lightFg, darkBg, darkFg, paper, accent } = sources
		  const ramps = neutralRamps(lightBg, lightFg, darkBg, darkFg, paper)
		  const tokens = {}

		  for (const [family, rampKey] of [['neutral-bluish', 'bluish'], ['neutral', 'plain']]) {
		    const stops = family === 'neutral' ? PLAIN_NEUTRAL_STOPS : NEUTRAL_BLUISH_STOPS
		    const ramp = ramps[rampKey]
		    for (const stop of stops) {
		      const label = FAMILY_STOPS[family].find((l) => Number.parseInt(l, 10) === stop)
		      if (label === undefined) throw new Error(`${family}: no label for stop ${stop}`)
		      tokens[STATIC(family, label)] = { light: ramp.light[stop], dark: ramp.dark[stop] }
		    }
		  }

		  for (const family of [...SEMANTIC_FAMILIES, ACCENT_FAMILY]) {
		    const base = sources[family]
		    if (!base) throw new Error(`sources.${family} is missing`)
		    const built = buildFamily(FAMILY_STOPS[family], base.light, base.dark, lightBg, darkBg)
		    for (const [label, value] of Object.entries(built)) {
		      // DSH ships a `50p` twin of `50`; nudge it so the two stops stay distinct.
		      tokens[STATIC(family, label)] = label.endsWith('p')
		        ? { light: mix(value.light, lightFg, 0.04), dark: mix(value.dark, darkFg, 0.04) }
		        : value
		    }
		  }

		  return tokens
		}
		// <<< inlined:ramp+ladder

		const PRESETS = [
				{
						"id": "flexoki",
						"label": "Flexoki",
						"theme": {
								"light": "Flexoki Light",
								"dark": "Flexoki Dark"
						},
						"sources": {
								"lightBg": "#f5f3ed",
								"lightFg": "#2f312d",
								"darkBg": "#100f0f",
								"darkFg": "#cecdc3",
								"paper": "#fffcf0",
								"red": {
										"light": "#af3029",
										"dark": "#d14d41"
								},
								"green": {
										"light": "#66800b",
										"dark": "#879a39"
								},
								"amber": {
										"light": "#ad8301",
										"dark": "#d0a215"
								},
								"blue": {
										"light": "#205ea6",
										"dark": "#4385be"
								},
								"deepseek": {
										"light": "#3d755d",
										"dark": "#4385be"
								}
						},
						"preview": {
								"lightBg": "#f5f3ed",
								"darkBg": "#100f0f",
								"lightFg": "#2f312d",
								"darkFg": "#cecdc3",
								"lightAccent": "#3d755d",
								"darkAccent": "#4385be"
						}
				},
				{
						"id": "catppuccin",
						"label": "Catppuccin",
						"theme": {
								"light": "Catppuccin Latte",
								"dark": "Catppuccin Mocha"
						},
						"sources": {
								"lightBg": "#eff1f5",
								"lightFg": "#4c4f69",
								"darkBg": "#1e1e2e",
								"darkFg": "#cdd6f4",
								"paper": "#eff1f5",
								"red": {
										"light": "#d20f39",
										"dark": "#f38ba8"
								},
								"green": {
										"light": "#40a02b",
										"dark": "#a6e3a1"
								},
								"amber": {
										"light": "#df8e1d",
										"dark": "#f9e2af"
								},
								"blue": {
										"light": "#1e66f5",
										"dark": "#89b4fa"
								},
								"deepseek": {
										"light": "#1e66f5",
										"dark": "#89b4fa"
								}
						},
						"preview": {
								"lightBg": "#eff1f5",
								"darkBg": "#1e1e2e",
								"lightFg": "#4c4f69",
								"darkFg": "#cdd6f4",
								"lightAccent": "#1e66f5",
								"darkAccent": "#89b4fa"
						}
				},
				{
						"id": "gruvbox",
						"label": "Gruvbox",
						"theme": {
								"light": "Gruvbox Light",
								"dark": "Gruvbox Dark"
						},
						"sources": {
								"lightBg": "#fbf1c7",
								"lightFg": "#3c3836",
								"darkBg": "#282828",
								"darkFg": "#ebdbb2",
								"paper": "#fbf1c7",
								"red": {
										"light": "#cc241d",
										"dark": "#cc241d"
								},
								"green": {
										"light": "#98971a",
										"dark": "#98971a"
								},
								"amber": {
										"light": "#d79921",
										"dark": "#d79921"
								},
								"blue": {
										"light": "#458588",
										"dark": "#458588"
								},
								"deepseek": {
										"light": "#458588",
										"dark": "#458588"
								}
						},
						"preview": {
								"lightBg": "#fbf1c7",
								"darkBg": "#282828",
								"lightFg": "#3c3836",
								"darkFg": "#ebdbb2",
								"lightAccent": "#458588",
								"darkAccent": "#458588"
						}
				},
				{
						"id": "everforest",
						"label": "Everforest",
						"theme": {
								"light": "Everforest Light Med",
								"dark": "Everforest Dark Hard"
						},
						"sources": {
								"lightBg": "#efebd4",
								"lightFg": "#5c6a72",
								"darkBg": "#1e2326",
								"darkFg": "#d3c6aa",
								"paper": "#efebd4",
								"red": {
										"light": "#e67e80",
										"dark": "#e67e80"
								},
								"green": {
										"light": "#9ab373",
										"dark": "#a7c080"
								},
								"amber": {
										"light": "#c1a266",
										"dark": "#dbbc7f"
								},
								"blue": {
										"light": "#7fbbb3",
										"dark": "#7fbbb3"
								},
								"deepseek": {
										"light": "#7fbbb3",
										"dark": "#7fbbb3"
								}
						},
						"preview": {
								"lightBg": "#efebd4",
								"darkBg": "#1e2326",
								"lightFg": "#5c6a72",
								"darkFg": "#d3c6aa",
								"lightAccent": "#7fbbb3",
								"darkAccent": "#7fbbb3"
						}
				},
				{
						"id": "github",
						"label": "GitHub",
						"theme": {
								"light": "GitHub Light Default",
								"dark": "GitHub Dark Default"
						},
						"sources": {
								"lightBg": "#ffffff",
								"lightFg": "#1f2328",
								"darkBg": "#0d1117",
								"darkFg": "#e6edf3",
								"paper": "#ffffff",
								"red": {
										"light": "#cf222e",
										"dark": "#ff7b72"
								},
								"green": {
										"light": "#116329",
										"dark": "#3fb950"
								},
								"amber": {
										"light": "#4d2d00",
										"dark": "#d29922"
								},
								"blue": {
										"light": "#0969da",
										"dark": "#58a6ff"
								},
								"deepseek": {
										"light": "#0969da",
										"dark": "#58a6ff"
								}
						},
						"preview": {
								"lightBg": "#ffffff",
								"darkBg": "#0d1117",
								"lightFg": "#1f2328",
								"darkFg": "#e6edf3",
								"lightAccent": "#0969da",
								"darkAccent": "#58a6ff"
						}
				},
				{
						"id": "nord",
						"label": "Nord",
						"theme": {
								"light": "Nord Light",
								"dark": "Nord"
						},
						"sources": {
								"lightBg": "#e5e9f0",
								"lightFg": "#414858",
								"darkBg": "#2e3440",
								"darkFg": "#d8dee9",
								"paper": "#e5e9f0",
								"red": {
										"light": "#bf616a",
										"dark": "#bf616a"
								},
								"green": {
										"light": "#96b17f",
										"dark": "#a3be8c"
								},
								"amber": {
										"light": "#c5a565",
										"dark": "#ebcb8b"
								},
								"blue": {
										"light": "#81a1c1",
										"dark": "#81a1c1"
								},
								"deepseek": {
										"light": "#81a1c1",
										"dark": "#81a1c1"
								}
						},
						"preview": {
								"lightBg": "#e5e9f0",
								"darkBg": "#2e3440",
								"lightFg": "#414858",
								"darkFg": "#d8dee9",
								"lightAccent": "#81a1c1",
								"darkAccent": "#81a1c1"
						}
				},
				{
						"id": "rose-pine",
						"label": "Rosé Pine",
						"theme": {
								"light": "Rose Pine Dawn",
								"dark": "Rose Pine Moon"
						},
						"sources": {
								"lightBg": "#faf4ed",
								"lightFg": "#575279",
								"darkBg": "#232136",
								"darkFg": "#e0def4",
								"paper": "#faf4ed",
								"red": {
										"light": "#b4637a",
										"dark": "#eb6f92"
								},
								"green": {
										"light": "#286983",
										"dark": "#3e8fb0"
								},
								"amber": {
										"light": "#ea9d34",
										"dark": "#f6c177"
								},
								"blue": {
										"light": "#56949f",
										"dark": "#9ccfd8"
								},
								"deepseek": {
										"light": "#56949f",
										"dark": "#9ccfd8"
								}
						},
						"preview": {
								"lightBg": "#faf4ed",
								"darkBg": "#232136",
								"lightFg": "#575279",
								"darkFg": "#e0def4",
								"lightAccent": "#56949f",
								"darkAccent": "#9ccfd8"
						}
				},
				{
						"id": "kanagawa",
						"label": "Kanagawa",
						"theme": {
								"light": "Kanagawa Lotus",
								"dark": "Kanagawa Wave"
						},
						"sources": {
								"lightBg": "#f2ecbc",
								"lightFg": "#545464",
								"darkBg": "#1f1f28",
								"darkFg": "#dcd7ba",
								"paper": "#f2ecbc",
								"red": {
										"light": "#c84053",
										"dark": "#c34043"
								},
								"green": {
										"light": "#6f894e",
										"dark": "#76946a"
								},
								"amber": {
										"light": "#77713f",
										"dark": "#c0a36e"
								},
								"blue": {
										"light": "#4d699b",
										"dark": "#7e9cd8"
								},
								"deepseek": {
										"light": "#4d699b",
										"dark": "#7e9cd8"
								}
						},
						"preview": {
								"lightBg": "#f2ecbc",
								"darkBg": "#1f1f28",
								"lightFg": "#545464",
								"darkFg": "#dcd7ba",
								"lightAccent": "#4d699b",
								"darkAccent": "#7e9cd8"
						}
				},
				{
						"id": "modus",
						"label": "Modus",
						"theme": {
								"light": "Modus Operandi Tinted",
								"dark": "Modus Vivendi Tinted"
						},
						"sources": {
								"lightBg": "#fbf7f0",
								"lightFg": "#000000",
								"darkBg": "#0d0e1c",
								"darkFg": "#ffffff",
								"paper": "#fbf7f0",
								"red": {
										"light": "#a60000",
										"dark": "#ff5f59"
								},
								"green": {
										"light": "#006800",
										"dark": "#44bc44"
								},
								"amber": {
										"light": "#6f5500",
										"dark": "#d0bc00"
								},
								"blue": {
										"light": "#0031a9",
										"dark": "#2fafff"
								},
								"deepseek": {
										"light": "#0031a9",
										"dark": "#2fafff"
								}
						},
						"preview": {
								"lightBg": "#fbf7f0",
								"darkBg": "#0d0e1c",
								"lightFg": "#000000",
								"darkFg": "#ffffff",
								"lightAccent": "#0031a9",
								"darkAccent": "#2fafff"
						}
				},
				{
						"id": "atom-one",
						"label": "Atom One",
						"theme": {
								"light": "Atom One Light",
								"dark": "Atom One Dark"
						},
						"sources": {
								"lightBg": "#f9f9f9",
								"lightFg": "#2a2c33",
								"darkBg": "#21252b",
								"darkFg": "#abb2bf",
								"paper": "#f9f9f9",
								"red": {
										"light": "#de3e35",
										"dark": "#e06c75"
								},
								"green": {
										"light": "#3f953a",
										"dark": "#98c379"
								},
								"amber": {
										"light": "#d2b67c",
										"dark": "#e5c07b"
								},
								"blue": {
										"light": "#2f5af3",
										"dark": "#61afef"
								},
								"deepseek": {
										"light": "#2f5af3",
										"dark": "#61afef"
								}
						},
						"preview": {
								"lightBg": "#f9f9f9",
								"darkBg": "#21252b",
								"lightFg": "#2a2c33",
								"darkFg": "#abb2bf",
								"lightAccent": "#2f5af3",
								"darkAccent": "#61afef"
						}
				}
		]
		const PRESET_BY_ID = new Map(PRESETS.map((p) => [p.id, p]))

		/**
		 * Font stacks come from ~/.codex/config.toml at build time. They are plain
		 * strings here; the pair coercion below is the ONLY place a font value becomes
		 * a theme token, because ctx.theme.overrideTokens rejects bare strings with a
		 * teaching error — and that error aborts the whole web boot, not just one row.
		 */
		const FONTS_RAW = {
				"--dsw-font-family": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
				"--ds-font-family-code": "\"JetBrainsMono Nerd Font\", \"SFMono-Regular\", Menlo, Consolas, \"PingFang SC\", monospace"
		}

		/** Both faces are written by one plugin-owned stylesheet rule. */
		const FONT_STYLE_ID = 'codex-theme-fonts'
		const DEFAULT_UI_FONT = FONTS_RAW['--dsw-font-family'] || '-apple-system, BlinkMacSystemFont, "PingFang SC", "Segoe UI", sans-serif'
		const DEFAULT_CODE_FONT = FONTS_RAW['--ds-font-family-code'] || 'ui-monospace, SFMono-Regular, Menlo, monospace'
		const FALLBACK_UI = '-apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Helvetica Neue", Arial, sans-serif'
		const FALLBACK_CODE = 'ui-monospace, SFMono-Regular, Menlo, Monaco, "Cascadia Mono", "PingFang SC", monospace'
		const stackOf = (fallback, families) => families.map((family) => '"' + family + '"').join(', ') + ', ' + fallback
		const codeStack = (...families) => stackOf(FALLBACK_CODE, families)
		const uiStack = (...families) => stackOf(FALLBACK_UI, families)
		/**
		 * A DSH plugin cannot ship a font file — the bundle route only serves the
		 * package's own client script chunks — so the list is limited to families
		 * the machine may
		 * already have. Every entry keeps a real fallback chain, and availability is
		 * measured at runtime so the menu never implies a missing font will work.
		 */
		const hasFont = (() => {
			let cache
			return (families) => {
				if (cache === undefined) {
					try {
						cache = document.createElement('canvas').getContext('2d') || null
					} catch {
						cache = null
					}
				}
				if (cache === null) return true
				const probe = 'mmmmmmmmmmlliWW'
				const width = (stack) => {
					cache.font = '72px ' + stack
					return cache.measureText(probe).width
				}
				// Two baselines on purpose. Comparing a monospace family against the
				// monospace baseline alone can miss it: two different mono faces often
				// share the exact same advance width. Any installed family differs from a
				// proportional baseline, so an OR across both cannot miss one — and a
				// missing family falls back identically to both, so it cannot false-positive.
				const mono = width('monospace')
				const sans = width('sans-serif')
				return families.some((family) => {
					const quoted = '"' + family + '"'
					return Math.abs(width(quoted + ', monospace') - mono) > 0.5
						|| Math.abs(width(quoted + ', sans-serif') - sans) > 0.5
				})
			}
		})()

		/** Proportional faces for the body text; the first entry keeps DSH's own stack. */
		const ALL_UI_FONTS = [
			{ id: 'default', label: '默认', ui: DEFAULT_UI_FONT, always: true },
			{ id: 'system', label: '系统', ui: FALLBACK_UI, always: true },
			{ id: 'pingfang', label: '苹方', families: ['PingFang SC'], ui: uiStack('PingFang SC') },
			{ id: 'hiragino', label: '冬青黑体', families: ['Hiragino Sans GB'], ui: uiStack('Hiragino Sans GB') },
			{ id: 'helvetica', label: 'Helvetica Neue', families: ['Helvetica Neue'], ui: uiStack('Helvetica Neue') },
			{ id: 'arial', label: 'Arial', families: ['Arial'], ui: uiStack('Arial') },
			{ id: 'georgia', label: 'Georgia', families: ['Georgia'], ui: uiStack('Georgia') },
			{ id: 'songti', label: '宋体', families: ['Songti SC'], ui: uiStack('Songti SC') },
			{ id: 'kaiti', label: '楷体', families: ['Kaiti SC'], ui: uiStack('Kaiti SC') },
			{ id: 'inter', label: 'Inter', families: ['Inter'], ui: uiStack('Inter') },
			{ id: 'geist-ui', label: 'Geist', families: ['Geist'], ui: uiStack('Geist') },
			{ id: 'source-han', label: '思源黑体', families: ['Source Han Sans SC', 'Noto Sans SC'], ui: uiStack('Source Han Sans SC', 'Noto Sans SC') },
		]

		const ALL_CODE_FONTS = [
			{ id: 'default', label: '默认', code: DEFAULT_CODE_FONT, always: true },
			{ id: 'system', label: '系统等宽', code: FALLBACK_CODE, always: true },
			{ id: 'jetbrains', label: 'JetBrains Mono', families: ['JetBrainsMono Nerd Font', 'JetBrains Mono'], code: codeStack('JetBrainsMono Nerd Font', 'JetBrains Mono') },
			{ id: 'fira', label: 'Fira Code', families: ['FiraCode Nerd Font', 'Fira Code'], code: codeStack('FiraCode Nerd Font', 'Fira Code') },
			{ id: 'cascadia', label: 'Cascadia Code', families: ['Cascadia Code NF', 'Cascadia Code', 'Cascadia Mono'], code: codeStack('Cascadia Code NF', 'Cascadia Code', 'Cascadia Mono') },
			{ id: 'hack', label: 'Hack', families: ['Hack Nerd Font', 'Hack'], code: codeStack('Hack Nerd Font', 'Hack') },
			{ id: 'plex', label: 'IBM Plex Mono', families: ['IBM Plex Mono'], code: codeStack('IBM Plex Mono') },
			{ id: 'source', label: 'Source Code Pro', families: ['Source Code Pro'], code: codeStack('Source Code Pro') },
			{ id: 'geist', label: 'Geist Mono', families: ['Geist Mono'], code: codeStack('Geist Mono') },
			{ id: 'maple', label: 'Maple Mono', families: ['Maple Mono NF', 'Maple Mono'], code: codeStack('Maple Mono NF', 'Maple Mono') },
			{ id: 'victor', label: 'Victor Mono', families: ['Victor Mono'], code: codeStack('Victor Mono') },
			{ id: 'lxgw', label: '霞鹜文楷等宽', families: ['LXGW WenKai Mono', 'LXGW WenKai Mono TC'], code: codeStack('LXGW WenKai Mono', 'LXGW WenKai Mono TC') },
		]
		const fontInstalled = (choice) => choice.always === true || !choice.families || hasFont(choice.families)
		/**
		 * Only families this machine actually has. Offering a font that silently falls
		 * back to another one reads as a broken control, so the list is what works.
		 */
		const UI_FONTS = ALL_UI_FONTS.filter(fontInstalled)
		const CODE_FONTS = ALL_CODE_FONTS.filter(fontInstalled)

		const read = (key, fallback) => {
			try {
				const value = localStorage.getItem(key)
				return value === null || value === '' ? fallback : value
			}
			catch {
				return fallback
			}
		}

		const write = (key, value) => {
			try {
				if (value === null || value === '') localStorage.removeItem(key)
				else localStorage.setItem(key, value)
			}
			catch {}
		}

		const HEX = /^#[0-9a-fA-F]{6}$/
		const customValues = () => Object.fromEntries(
			Object.entries(KEY_CUSTOM).map(([field, key]) => [field, read(key, null)]),
		)

		const isEnabled = () => read(KEY_ENABLED, '1') !== '0'
		const activePresetId = () => {
			const id = read(KEY_PRESET, DEFAULT_PRESET)
			return PRESET_BY_ID.has(id) ? id : DEFAULT_PRESET
		}
		const activeCodeFontId = () => {
			const id = read(KEY_FONT, 'default')
			return CODE_FONTS.some((choice) => choice.id === id) ? id : 'default'
		}
		const activeUiFontId = () => {
			const id = read(KEY_UI_FONT, 'default')
			return UI_FONTS.some((choice) => choice.id === id) ? id : 'default'
		}

		const notify = () => window.dispatchEvent(new Event(EVENT))

		/**
		 * A preset's anchors with the user's overrides applied. Only background,
		 * foreground and accent are overridable; the semantic families keep the
		 * preset's own values so a retint never destroys diff/error semantics.
		 */
		const effectiveSources = (preset, custom) => {
			const sources = { ...preset.sources }
			if (custom.accent && HEX.test(custom.accent)) {
				sources[ACCENT_FAMILY] = { light: custom.accent, dark: custom.accent }
			}
			if (custom.lightBg && HEX.test(custom.lightBg)) sources.lightBg = custom.lightBg
			if (custom.lightFg && HEX.test(custom.lightFg)) sources.lightFg = custom.lightFg
			if (custom.darkBg && HEX.test(custom.darkBg)) sources.darkBg = custom.darkBg
			if (custom.darkFg && HEX.test(custom.darkFg)) sources.darkFg = custom.darkFg
			return sources
		}

		const tokenCache = new Map()
		const tokensFor = (preset, custom) => {
			const key = preset.id + '|' + JSON.stringify(custom)
			const hit = tokenCache.get(key)
			if (hit) return hit
			const tokens = buildTokens(effectiveSources(preset, custom))
			tokenCache.set(key, tokens)
			return tokens
		}

		/** The two contrast readings the custom controls surface as live feedback. */
		const contrastReadout = (sources) => {
			const tokens = buildTokens(sources)
			const at = (stop, mode) => tokens['--dsw-static-neutral-bluish-' + String(stop).padStart(2, '0')][mode]
			return {
				light: contrast(at(1000, 'light'), at(0, 'light')),
				dark: contrast(at(50, 'dark'), at(950, 'dark')),
			}
		}

		// ─────────────────────────────── UI primitives ───────────────────────────────

		const SPACE = 8

		// Every surface, radius, border and shadow below comes from the official design
		// platform, so this page follows the host theme in both light and dark instead
		// of carrying its own palette.
		const groupStyle = {
			border: '1px solid var(--dsw-alias-settings-card-stroke, var(--dsw-alias-border-l2))',
			borderRadius: 'var(--dsw-radius-md)',
			background: 'var(--dsw-alias-settings-card-fill, var(--dsw-alias-bg-layer-1))',
		}
		const headStyle = {
			display: 'flex', alignItems: 'center', justifyContent: 'space-between',
			gap: SPACE * 2, padding: '12px 16px',
		}
		const rowStyle = {
			display: 'flex', alignItems: 'center', justifyContent: 'space-between',
			gap: '8px 16px', padding: '10px 16px', minHeight: 44, flexWrap: 'wrap',
			borderTop: '1px solid var(--dsw-alias-border-l2)',
		}
		const footStyle = {
			display: 'flex', alignItems: 'center', justifyContent: 'space-between',
			gap: SPACE * 1.5, padding: '10px 16px', flexWrap: 'wrap',
			borderTop: '1px solid var(--dsw-alias-border-l2)',
		}
		const titleStyle = { margin: 0, fontSize: 14, fontWeight: 600, color: 'var(--dsw-alias-label-primary)' }
		const subStyle = { marginTop: 2, fontSize: 12.5, color: 'var(--dsw-alias-label-tertiary)' }
		const labelStyle = { fontSize: 13.5, color: 'var(--dsw-alias-label-primary)', flex: 'none' }
		const ctrlStyle = { display: 'flex', alignItems: 'center', gap: SPACE, flexWrap: 'wrap', justifyContent: 'flex-end', marginLeft: 'auto' }
		// A fixed stack on purpose: the settings panel must not reflow when the CODE
		// font changes, or the whole page visibly jumps on every font switch.
		const UI_MONO = 'ui-monospace, SFMono-Regular, Menlo, Monaco, monospace'
		const hexStyle = { fontFamily: UI_MONO, fontSize: 12, color: 'var(--dsw-alias-label-secondary)' }
		const slashStyle = { color: 'var(--dsw-alias-label-tertiary)', fontSize: 12 }
		const dropdownStyle = {
			display: 'inline-flex', alignItems: 'center', justifyContent: 'space-between', gap: SPACE * 1.5,
			minWidth: 0, padding: '5px 10px', border: '1px solid var(--dsw-alias-border-l2)',
			borderRadius: 'var(--dsw-radius-sm)', background: 'none', color: 'var(--dsw-alias-label-primary)',
			font: 'inherit', cursor: 'pointer',
		}
		const menuStyle = {
			position: 'absolute', right: 0, top: 'calc(100% + 4px)', zIndex: 30, minWidth: 224,
			maxHeight: 264, overflowY: 'auto', padding: 6,
			background: 'var(--dsw-alias-bg-layer-2)', border: '1px solid var(--dsw-alias-border-l3)',
			borderRadius: 'var(--dsw-radius-md)', boxShadow: 'var(--dsw-shadow-lv3)',
		}
		const menuItemStyle = (highlighted) => ({
			display: 'flex', alignItems: 'center', gap: SPACE, padding: '6px 8px',
			borderRadius: 'var(--dsw-radius-sm)', cursor: 'pointer',
			background: highlighted ? 'var(--dsw-alias-interactive-bg-hover)' : 'none',
		})
		const pairChipStyle = {
			display: 'inline-flex', width: 34, height: 22, flex: 'none',
			borderRadius: 'var(--dsw-radius-xs)', overflow: 'hidden',
			border: '1px solid var(--dsw-alias-border-l2)',
		}
		const aaStyle = {
			display: 'inline-flex', alignItems: 'center', justifyContent: 'center', flex: 'none',
			width: 22, height: 22, borderRadius: '50%', fontSize: 12, fontWeight: 700,
			color: 'var(--dsw-static-deepseek-500)', background: 'var(--dsw-alias-interactive-bg-hover)',
		}
		const focusRing = {
			outline: '2px solid var(--dsw-focus-ring-color, var(--dsw-alias-state-business-primary))',
			outlineOffset: 2,
		}

		const onFocusRing = (e) => Object.assign(e.currentTarget.style, focusRing)
		const onBlurRing = (e) => Object.assign(e.currentTarget.style, { outline: 'none' })

		function Switch({ checked, onChange, label }) {
			return h('button', {
				type: 'button',
				role: 'switch',
				'aria-checked': checked,
				'aria-label': label,
				onClick: () => onChange(!checked),
				onFocus: onFocusRing,
				onBlur: onBlurRing,
				style: {
					position: 'relative', width: 44, height: 24, flex: 'none', padding: 0, border: 0,
					borderRadius: 999, cursor: 'pointer',
					background: checked ? 'var(--dsw-alias-brand-primary)' : 'var(--dsw-alias-bg-multi-select)',
					transition: 'background 150ms ease',
				},
			}, h('span', {
				'aria-hidden': true,
				style: {
					position: 'absolute', top: 2, left: checked ? 22 : 2, width: 20, height: 20, borderRadius: '50%',
					background: 'var(--dsw-alias-label-primary-foreground)', transition: 'left 150ms ease',
				},
			}))
		}

		const swatchBox = {
			width: 26, height: 22, flex: 'none',
			border: '1px solid var(--dsw-alias-border-l2)', borderRadius: 'var(--dsw-radius-xs)',
		}

		/**
		 * A native color well — on macOS the system picker, keyboard reachable — or a
		 * plain swatch when the value is not editable. A disabled input still reads as a
		 * control the user ought to be able to press; a swatch reads as a value.
		 */
		function ColorControl({ label, value, onChange, readOnly }) {
			if (readOnly) {
				return h('span', { 'aria-hidden': true, style: { ...swatchBox, background: value } })
			}
			return h('input', {
				type: 'color',
				'aria-label': label,
				value,
				onChange: (e) => onChange(e.target.value),
				onFocus: onFocusRing,
				onBlur: onBlurRing,
				style: { ...swatchBox, padding: 0, background: 'none', cursor: 'pointer' },
			})
		}

		/** A preset's light and dark page colour side by side: the whole reading of a theme. */
		function pairChipOf(preset) {
			return h('span', { 'aria-hidden': true, style: pairChipStyle },
				h('span', { style: { flex: 1, background: preset.preview.lightBg } }),
				h('span', { style: { flex: 1, background: preset.preview.darkBg } }))
		}

		/**
		 * A secondary action, rendered as text rather than a bordered button. The panel
		 * already carries one bordered control per row; a second container in the footer
		 * competes with them for attention.
		 */
		function TextAction({ label, hint, disabled, onClick }) {
			const [hover, setHover] = React.useState(false)
			return h('button', {
				type: 'button', disabled, title: hint,
				onClick,
				onMouseEnter: () => setHover(true),
				onMouseLeave: () => setHover(false),
				onFocus: onFocusRing, onBlur: onBlurRing,
				style: {
					border: 0, padding: '4px 8px', margin: '-4px -8px',
					borderRadius: 'var(--dsw-radius-xs)', font: 'inherit', fontSize: 13,
					background: !disabled && hover ? 'var(--dsw-alias-interactive-bg-hover)' : 'none',
					color: disabled ? 'var(--dsw-alias-label-tertiary)' : 'var(--dsw-alias-label-secondary)',
					cursor: disabled ? 'default' : 'pointer',
				},
			}, label)
		}

		/**
		 * One listbox-style dropdown, owning its open state, outside-click dismissal and
		 * keyboard behaviour: ArrowDown/Up move, Enter selects, Esc closes and returns
		 * focus to the trigger. Tab closes without stealing the next focus stop.
		 */
		function Dropdown({ label, value, options, onSelect, disabled, trigger }) {
			const [open, setOpen] = React.useState(false)
			const [active, setActive] = React.useState(0)
			const wrapRef = React.useRef(null)
			const btnRef = React.useRef(null)

			React.useEffect(() => {
				if (!open) return undefined
				const onDocDown = (event) => {
					if (wrapRef.current && !wrapRef.current.contains(event.target)) setOpen(false)
				}
				document.addEventListener('mousedown', onDocDown)
				return () => document.removeEventListener('mousedown', onDocDown)
			}, [open])

			const close = (refocus) => {
				setOpen(false)
				if (refocus && btnRef.current) btnRef.current.focus()
			}
			const commit = (id) => {
				onSelect(id)
				close(true)
			}
			const onKeyDown = (event) => {
				if (!open) {
					if (event.key === 'ArrowDown' || event.key === 'Enter' || event.key === ' ') {
						event.preventDefault()
						const index = options.findIndex((option) => option.id === value)
						setActive(index < 0 ? 0 : index)
						setOpen(true)
					}
					return
				}
				if (event.key === 'Escape') {
					event.preventDefault()
					close(true)
					return
				}
				if (event.key === 'Tab') {
					setOpen(false)
					return
				}
				if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
					event.preventDefault()
					const step = event.key === 'ArrowDown' ? 1 : -1
					setActive((index) => (index + step + options.length) % options.length)
					return
				}
				if (event.key === 'Enter' || event.key === ' ') {
					event.preventDefault()
					const option = options[active]
					if (option) commit(option.id)
				}
			}

			return h('div', { ref: wrapRef, style: { position: 'relative', minWidth: 0 } },
				h('button', {
					type: 'button', ref: btnRef, disabled,
					'aria-haspopup': 'listbox', 'aria-expanded': open, 'aria-label': label,
					onClick: () => (open ? close(false) : setOpen(true)),
					onKeyDown, onFocus: onFocusRing, onBlur: onBlurRing,
					style: { ...dropdownStyle, cursor: disabled ? 'default' : 'pointer', opacity: disabled ? 0.5 : 1 },
				},
					trigger,
					h('span', { 'aria-hidden': true, style: { color: 'var(--dsw-alias-label-tertiary)', fontSize: 10 } }, open ? '▲' : '▼'),
				),
				open ? h('div', { role: 'listbox', 'aria-label': label, style: menuStyle },
					options.map((option, index) => h('div', {
						key: option.id,
						role: 'option',
						'aria-selected': option.id === value,
						onMouseEnter: () => setActive(index),
						onClick: () => commit(option.id),
						style: menuItemStyle(index === active || option.id === value),
					},
						option.swatch || null,
						h('span', { style: { flex: 1, fontSize: 13, color: 'var(--dsw-alias-label-primary)' } }, option.label),
						option.id === value
							? h('span', { 'aria-hidden': true, style: { color: 'var(--dsw-static-deepseek-500)', fontSize: 12 } }, '✓')
							: null,
					))) : null,
			)
		}

		function Section() {
			const [enabled, setEnabled] = React.useState(isEnabled)
			const [presetId, setPresetId] = React.useState(activePresetId)
			const [uiFontId, setUiFontId] = React.useState(activeUiFontId)
			const [fontId, setFontId] = React.useState(activeCodeFontId)
			const [custom, setCustom] = React.useState(customValues)

			const preset = PRESET_BY_ID.get(presetId) ?? PRESETS[0]
			const sources = effectiveSources(preset, custom)
			const ratios = contrastReadout(sources)
			const worst = Math.min(ratios.light, ratios.dark)
			const customised = Object.values(custom).some((value) => value !== null)
			const accentFollows = !(custom.accent && HEX.test(custom.accent))
			const effectiveAccent = accentFollows ? preset.sources[ACCENT_FAMILY].light : custom.accent
			const labelOf = (list, id) => (list.find((entry) => entry.id === id) ?? list[0]).label
			const uiFontLabel = labelOf(UI_FONTS, uiFontId)
			const codeFontLabel = labelOf(CODE_FONTS, fontId)

			const pick = (id) => {
				write(KEY_PRESET, id)
				setPresetId(id)
				notify()
			}
			const pickFont = (id) => {
				write(KEY_FONT, id)
				setFontId(id)
				notify()
			}
			const pickUiFont = (id) => {
				write(KEY_UI_FONT, id)
				setUiFontId(id)
				notify()
			}
			const toggle = (next) => {
				write(KEY_ENABLED, next ? '1' : '0')
				setEnabled(next)
				notify()
			}
			const setField = (field, value) => {
				write(KEY_CUSTOM[field], value)
				setCustom((prev) => ({ ...prev, [field]: value }))
				notify()
			}
			const resetCustom = () => {
				for (const key of Object.values(KEY_CUSTOM)) write(key, '')
				setCustom(Object.fromEntries(Object.keys(KEY_CUSTOM).map((field) => [field, null])))
				notify()
			}

			const presetOptions = PRESETS.map((entry) => ({
				id: entry.id,
				label: entry.label,
				swatch: pairChipOf(entry),
			}))
			const accentOptions = [
				{ id: 'follow', label: '跟随主题' },
				{ id: 'custom', label: '自定义' },
			]
			const uiFontOptions = UI_FONTS.map((entry) => ({ id: entry.id, label: entry.label }))
			const fontOptions = CODE_FONTS.map((entry) => ({ id: entry.id, label: entry.label }))

			return h('div', { style: { paddingBottom: SPACE * 3 } },
				h('div', { style: groupStyle },
					h('div', { style: headStyle },
						h('div', { style: { minWidth: 0 } },
							h('div', { style: titleStyle }, '视觉风格'),
							h('div', { style: subStyle }, '配色与字体'),
						),
						h(Switch, { checked: enabled, onChange: toggle, label: '启用主题' }),
					),

					enabled ? null : h('div', { style: { ...rowStyle, fontSize: 12.5, color: 'var(--dsw-alias-label-tertiary)' } },
						'主题已关闭，下面的设置暂不生效。'),

					h('div', { style: { opacity: enabled ? 1 : 0.55 } },
						h('div', { style: rowStyle },
							h('span', { style: labelStyle }, '主题'),
							h('span', { style: ctrlStyle },
								h(Dropdown, {
									label: '主题预设',
									value: presetId,
									options: presetOptions,
									onSelect: pick,
									disabled: !enabled,
									trigger: h('span', { style: { display: 'flex', alignItems: 'center', gap: SPACE } },
										h('span', { 'aria-hidden': true, style: aaStyle }, 'Aa'),
										h('span', { style: { fontSize: 13.5 } }, preset.label)),
								}),
							),
						),

						h('div', { style: rowStyle },
							h('span', { style: labelStyle }, '强调色'),
							h('span', { style: ctrlStyle },
								h(ColorControl, {
									label: '强调色',
									value: effectiveAccent,
									readOnly: !enabled || accentFollows,
									onChange: (value) => setField('accent', value),
								}),
								h('span', { style: hexStyle }, effectiveAccent.toUpperCase()),
								h(Dropdown, {
									label: '强调色来源',
									value: accentFollows ? 'follow' : 'custom',
									options: accentOptions,
									disabled: !enabled,
									onSelect: (id) => setField('accent', id === 'follow' ? '' : effectiveAccent),
									trigger: h('span', { style: { fontSize: 13 } }, accentFollows ? '跟随主题' : '自定义'),
								}),
							),
						),

						h('div', { style: rowStyle },
							h('span', { style: labelStyle }, '背景'),
							h('span', { style: ctrlStyle },
								h(ColorControl, { label: '浅色背景', value: sources.lightBg, readOnly: !enabled, onChange: (value) => setField('lightBg', value) }),
								h('span', { style: hexStyle }, sources.lightBg.toUpperCase()),
								h('span', { 'aria-hidden': true, style: slashStyle }, '/'),
								h(ColorControl, { label: '深色背景', value: sources.darkBg, readOnly: !enabled, onChange: (value) => setField('darkBg', value) }),
								h('span', { style: hexStyle }, sources.darkBg.toUpperCase()),
							),
						),

						h('div', { style: rowStyle },
							h('span', { style: labelStyle }, '前景'),
							h('span', { style: ctrlStyle },
								h(ColorControl, { label: '浅色前景', value: sources.lightFg, readOnly: !enabled, onChange: (value) => setField('lightFg', value) }),
								h('span', { style: hexStyle }, sources.lightFg.toUpperCase()),
								h('span', { 'aria-hidden': true, style: slashStyle }, '/'),
								h(ColorControl, { label: '深色前景', value: sources.darkFg, readOnly: !enabled, onChange: (value) => setField('darkFg', value) }),
								h('span', { style: hexStyle }, sources.darkFg.toUpperCase()),
							),
						),

						h('div', { style: rowStyle },
							h('span', { style: labelStyle }, '正文字体'),
							h('span', { style: ctrlStyle },
								h(Dropdown, {
									label: '正文字体',
									value: uiFontId,
									options: uiFontOptions,
									onSelect: pickUiFont,
									disabled: !enabled,
									trigger: h('span', { style: { fontSize: 13 } }, uiFontLabel),
								}),
							),
						),

						h('div', { style: rowStyle },
							h('span', { style: labelStyle }, '代码字体'),
							h('span', { style: ctrlStyle },
								h(Dropdown, {
									label: '代码字体',
									value: fontId,
									options: fontOptions,
									onSelect: pickFont,
									disabled: !enabled,
									trigger: h('span', { style: { fontSize: 13 } }, codeFontLabel),
								}),
							),
						),
					),

					h('div', { style: footStyle },
						h('span', { style: { display: 'flex', alignItems: 'center', gap: SPACE, flexWrap: 'wrap' } },
							h('span', { style: { fontSize: 12.5, color: 'var(--dsw-alias-label-tertiary)' } }, '正文对比度'),
							h('span', {
								role: 'status',
								style: {
									fontSize: 12, padding: '3px 9px', borderRadius: 999,
									border: '1px solid ' + (worst < 4.5 ? 'var(--dsw-alias-state-error-primary)' : 'var(--dsw-alias-border-l2)'),
									color: worst < 4.5 ? 'var(--dsw-alias-state-error-primary)' : 'var(--dsw-alias-label-secondary)',
								},
							}, '浅色 ' + ratios.light.toFixed(2) + ':1 · 深色 ' + ratios.dark.toFixed(2) + ':1'
								+ (worst < 4.5 ? ' · 低于 4.5:1' : ' · 达标')),
						),
						h(TextAction, {
							label: customised ? '清除自定义' : '未做自定义',
							hint: customised ? '只清除自定义色号，不改变已选预设' : '当前没有自定义色号',
							disabled: !customised,
							onClick: resetCustom,
						}),
					),
				),
			)
		}

		return {
			inject: ['theme', 'slots'],
			apply(ctx) {
				let disposeLayer = null
				let lastTokenKey = null

				/**
				 * The colour ramp goes through ctx.theme.overrideTokens — the sanctioned
				 * channel. It rewrites every token on body, so it is only worth doing when
				 * the palette itself changed.
				 */
				const syncTokens = () => {
					const key = (isEnabled() ? '1' : '0') + '|' + activePresetId() + '|' + JSON.stringify(customValues())
					if (key === lastTokenKey) return
					lastTokenKey = key
					if (disposeLayer) {
						disposeLayer()
						disposeLayer = null
					}
					if (!isEnabled()) return
					const preset = PRESET_BY_ID.get(activePresetId()) ?? PRESETS[0]
					disposeLayer = ctx.theme.overrideTokens(PACKAGE, tokensFor(preset, customValues()))
				}

				/**
				 * The code face is one variable, so it gets one stylesheet rule of our own
				 * instead of a theme republish. Rewriting a single rule costs one style
				 * recalc; republishing the theme re-renders the whole application, which is
				 * what made the page jump on every font change.
				 */
				const syncFont = () => {
					const existing = document.getElementById(FONT_STYLE_ID)
					if (!isEnabled()) {
						if (existing) existing.remove()
						return
					}
					const ui = UI_FONTS.find((entry) => entry.id === activeUiFontId()) ?? UI_FONTS[0]
					const code = CODE_FONTS.find((entry) => entry.id === activeCodeFontId()) ?? CODE_FONTS[0]
					const css = 'body{--dsw-font-family:' + ui.ui + ';--ds-font-family-code:' + code.code + '}'
					if (existing) {
						if (existing.textContent !== css) existing.textContent = css
						return
					}
					const tag = document.createElement('style')
					tag.id = FONT_STYLE_ID
					tag.dataset.plugin = PACKAGE
					tag.textContent = css
					document.head.appendChild(tag)
				}

				const sync = () => {
					syncTokens()
					syncFont()
				}

				sync()

				ctx.effect(() => {
					const onChanged = () => sync()
					window.addEventListener(EVENT, onChanged)
					return () => {
						window.removeEventListener(EVENT, onChanged)
						if (disposeLayer) {
							disposeLayer()
							disposeLayer = null
						}
						const tag = document.getElementById(FONT_STYLE_ID)
						if (tag) tag.remove()
					}
				}, 'codex-theme: token + code-face override')

				ctx.slots.inject('settings.section', () => ctx.slots.register({
					name: 'settings.section',
					id: 'codex-theme',
					order: 18,
					label: () => '主题',
				}, Section))
			},
		}
	},
})
