/**
 * Emit the installable bundle's client half from presets.json.
 *
 * Two things are inlined rather than imported or hand-copied, and both are
 * checked by tools/verify-runtime.mjs:
 *
 *   1. the preset source anchors from presets.json, and
 *   2. tools/lib/ramp.mjs + tools/lib/ladder.mjs, with `export ` stripped.
 *
 * Because the browser recomputes a custom theme through the same code that built
 * the shipped presets, the two can never drift. A plain-JS client half cannot
 * import them, so inlining is the only way to share one source.
 *
 *   node tools/build-presets.mjs && node tools/emit-plugin.mjs
 *
 * @see tools/release.mjs — a changed client.js needs a fresh URL because the
 * bundle is served `immutable` and its rev does not track file content.
 */
import fs from 'node:fs'
import path from 'node:path'
import { createHash } from 'node:crypto'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..')

const generated = JSON.parse(fs.readFileSync(path.join(root, 'presets.json'), 'utf8'))
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'plugin', 'package.json'), 'utf8'))
const PACKAGE = pkg.name

/**
 * A stamp of this generator plus the preset data, embedded in the artifact so
 * tools/verify-runtime.mjs can tell a freshly emitted bundle from a stale one.
 *
 * This exists because the client half is one big template literal: a stray backtick
 * in an emitted comment breaks this file at parse time, the write never happens, and
 * verification then happily passes against the PREVIOUS bundle.
 */
const buildStamp = createHash('sha1')
  .update(fs.readFileSync(fileURLToPath(import.meta.url)))
  .update(fs.readFileSync(path.join(root, 'presets.json')))
  .digest('hex')
  .slice(0, 12)

/**
 * Guard the contract that once took the whole app down: ctx.theme.overrideTokens
 * rejects a bare string, the throw happens inside the plugin callback, and the host
 * then reports "1 entry did not activate" for the entire web boot. Fail the build
 * here instead of shipping a bundle that can abort startup.
 */
for (const [name, value] of Object.entries(generated.fonts ?? {})) {
  const usable = typeof value === 'string'
    || (value !== null && typeof value === 'object'
      && typeof value.light === 'string' && typeof value.dark === 'string')
  if (!usable) {
    throw new Error('presets.json fonts["' + name + '"] must be a string or a { light, dark } pair of strings')
  }
}

/** Strip module syntax so the source can live inside a plain browser factory. */
function inlineModule(relativePath) {
  const source = fs.readFileSync(path.join(root, relativePath), 'utf8')
  return source
    .split('\n')
    .filter((line) => !/^import\s/.test(line))
    .join('\n')
    .replace(/^export (const|function|let) /gm, '$1 ')
    .trimEnd()
}

const MODULES = ['tools/lib/ramp.mjs', 'tools/lib/ladder.mjs'].map(inlineModule).join('\n\n')

const presets = generated.presets.map((preset) => ({
  id: preset.id,
  label: preset.label,
  theme: preset.theme,
  sources: preset.sources,
  preview: preset.preview,
}))

const client = `/* Generated by tools/emit-plugin.mjs — do not edit by hand. */
/* build ${buildStamp} */
/* Preset anchors come from presets.json; the color math below is tools/lib/ramp.mjs
   and tools/lib/ladder.mjs inlined verbatim, so runtime recomputation and the
   shipped presets share one implementation. */
window.__ModuleLoader__.load({
	id: ${JSON.stringify(PACKAGE)},
	factory: (require) => {
		const React = require('react')
		const h = React.createElement

		const PACKAGE = ${JSON.stringify(PACKAGE)}
		const KEY_ENABLED = 'codex-theme:enabled'
		const KEY_PRESET = 'codex-theme:preset'
		const KEY_FONT = 'codex-theme:font'
		const KEY_UI_FONT = 'codex-theme:ui-font'
		const KEY_CUSTOM = {
			accent: 'codex-theme:accent',
			lightBg: 'codex-theme:light-bg',
			lightFg: 'codex-theme:light-fg',
			darkBg: 'codex-theme:dark-bg',
			darkFg: 'codex-theme:dark-fg',
		}
		const EVENT = 'codex-theme:changed'
		const DEFAULT_PRESET = ${JSON.stringify(generated.defaultPreset)}

		// >>> inlined:ramp+ladder
		// tools/lib/ramp.mjs + tools/lib/ladder.mjs, with the export keyword stripped
${MODULES.replace(/^(?!$)/gm, '\t\t')}
		// <<< inlined:ramp+ladder

		const PRESETS = ${JSON.stringify(presets, null, '\t\t').replace(/\n/g, '\n\t\t')}
		const PRESET_BY_ID = new Map(PRESETS.map((p) => [p.id, p]))

		/**
		 * Font stacks come from ~/.codex/config.toml at build time. They are plain
		 * strings here; the pair coercion below is the ONLY place a font value becomes
		 * a theme token, because ctx.theme.overrideTokens rejects bare strings with a
		 * teaching error — and that error aborts the whole web boot, not just one row.
		 */
		const FONTS_RAW = ${JSON.stringify(generated.fonts, null, '\t\t').replace(/\n/g, '\n\t\t')}

		/** Both faces are written by one plugin-owned stylesheet rule. */
		const FONT_STYLE_ID = 'codex-theme-fonts'
		const DEFAULT_UI_FONT = FONTS_RAW['--dsw-font-family'] || '-apple-system, BlinkMacSystemFont, "PingFang SC", "Segoe UI", sans-serif'
		const DEFAULT_CODE_FONT = FONTS_RAW['--ds-font-family-code'] || 'ui-monospace, SFMono-Regular, Menlo, monospace'
		const FALLBACK_UI = '-apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Helvetica Neue", Arial, sans-serif'
		const FALLBACK_CODE = 'ui-monospace, SFMono-Regular, Menlo, Monaco, "Cascadia Mono", "PingFang SC", monospace'
		const stackOf = (fallback, families) => families.map((family) => '"' + family + '"').join(', ') + ', ' + fallback
		const codeStack = (...families) => stackOf(FALLBACK_CODE, families)
		const uiStack = (...families) => stackOf(FALLBACK_UI, families)
		/**
		 * A DSH plugin cannot ship a font file — the bundle route only serves the
		 * package's own client script chunks — so the list is limited to families
		 * the machine may
		 * already have. Every entry keeps a real fallback chain, and availability is
		 * measured at runtime so the menu never implies a missing font will work.
		 */
		const hasFont = (() => {
			let cache
			return (families) => {
				if (cache === undefined) {
					try {
						cache = document.createElement('canvas').getContext('2d') || null
					} catch {
						cache = null
					}
				}
				if (cache === null) return true
				const probe = 'mmmmmmmmmmlliWW'
				const width = (stack) => {
					cache.font = '72px ' + stack
					return cache.measureText(probe).width
				}
				// Two baselines on purpose. Comparing a monospace family against the
				// monospace baseline alone can miss it: two different mono faces often
				// share the exact same advance width. Any installed family differs from a
				// proportional baseline, so an OR across both cannot miss one — and a
				// missing family falls back identically to both, so it cannot false-positive.
				const mono = width('monospace')
				const sans = width('sans-serif')
				return families.some((family) => {
					const quoted = '"' + family + '"'
					return Math.abs(width(quoted + ', monospace') - mono) > 0.5
						|| Math.abs(width(quoted + ', sans-serif') - sans) > 0.5
				})
			}
		})()

		/** Proportional faces for the body text; the first entry keeps DSH's own stack. */
		const ALL_UI_FONTS = [
			{ id: 'default', label: '默认', ui: DEFAULT_UI_FONT, always: true },
			{ id: 'system', label: '系统', ui: FALLBACK_UI, always: true },
			{ id: 'pingfang', label: '苹方', families: ['PingFang SC'], ui: uiStack('PingFang SC') },
			{ id: 'hiragino', label: '冬青黑体', families: ['Hiragino Sans GB'], ui: uiStack('Hiragino Sans GB') },
			{ id: 'helvetica', label: 'Helvetica Neue', families: ['Helvetica Neue'], ui: uiStack('Helvetica Neue') },
			{ id: 'arial', label: 'Arial', families: ['Arial'], ui: uiStack('Arial') },
			{ id: 'georgia', label: 'Georgia', families: ['Georgia'], ui: uiStack('Georgia') },
			{ id: 'songti', label: '宋体', families: ['Songti SC'], ui: uiStack('Songti SC') },
			{ id: 'kaiti', label: '楷体', families: ['Kaiti SC'], ui: uiStack('Kaiti SC') },
			{ id: 'inter', label: 'Inter', families: ['Inter'], ui: uiStack('Inter') },
			{ id: 'geist-ui', label: 'Geist', families: ['Geist'], ui: uiStack('Geist') },
			{ id: 'source-han', label: '思源黑体', families: ['Source Han Sans SC', 'Noto Sans SC'], ui: uiStack('Source Han Sans SC', 'Noto Sans SC') },
		]

		const ALL_CODE_FONTS = [
			{ id: 'default', label: '默认', code: DEFAULT_CODE_FONT, always: true },
			{ id: 'system', label: '系统等宽', code: FALLBACK_CODE, always: true },
			{ id: 'jetbrains', label: 'JetBrains Mono', families: ['JetBrainsMono Nerd Font', 'JetBrains Mono'], code: codeStack('JetBrainsMono Nerd Font', 'JetBrains Mono') },
			{ id: 'fira', label: 'Fira Code', families: ['FiraCode Nerd Font', 'Fira Code'], code: codeStack('FiraCode Nerd Font', 'Fira Code') },
			{ id: 'cascadia', label: 'Cascadia Code', families: ['Cascadia Code NF', 'Cascadia Code', 'Cascadia Mono'], code: codeStack('Cascadia Code NF', 'Cascadia Code', 'Cascadia Mono') },
			{ id: 'hack', label: 'Hack', families: ['Hack Nerd Font', 'Hack'], code: codeStack('Hack Nerd Font', 'Hack') },
			{ id: 'plex', label: 'IBM Plex Mono', families: ['IBM Plex Mono'], code: codeStack('IBM Plex Mono') },
			{ id: 'source', label: 'Source Code Pro', families: ['Source Code Pro'], code: codeStack('Source Code Pro') },
			{ id: 'geist', label: 'Geist Mono', families: ['Geist Mono'], code: codeStack('Geist Mono') },
			{ id: 'maple', label: 'Maple Mono', families: ['Maple Mono NF', 'Maple Mono'], code: codeStack('Maple Mono NF', 'Maple Mono') },
			{ id: 'victor', label: 'Victor Mono', families: ['Victor Mono'], code: codeStack('Victor Mono') },
			{ id: 'lxgw', label: '霞鹜文楷等宽', families: ['LXGW WenKai Mono', 'LXGW WenKai Mono TC'], code: codeStack('LXGW WenKai Mono', 'LXGW WenKai Mono TC') },
		]
		const fontInstalled = (choice) => choice.always === true || !choice.families || hasFont(choice.families)
		/**
		 * Only families this machine actually has. Offering a font that silently falls
		 * back to another one reads as a broken control, so the list is what works.
		 */
		const UI_FONTS = ALL_UI_FONTS.filter(fontInstalled)
		const CODE_FONTS = ALL_CODE_FONTS.filter(fontInstalled)

		const read = (key, fallback) => {
			try {
				const value = localStorage.getItem(key)
				return value === null || value === '' ? fallback : value
			}
			catch {
				return fallback
			}
		}

		const write = (key, value) => {
			try {
				if (value === null || value === '') localStorage.removeItem(key)
				else localStorage.setItem(key, value)
			}
			catch {}
		}

		const HEX = /^#[0-9a-fA-F]{6}$/
		const customValues = () => Object.fromEntries(
			Object.entries(KEY_CUSTOM).map(([field, key]) => [field, read(key, null)]),
		)

		const isEnabled = () => read(KEY_ENABLED, '1') !== '0'
		const activePresetId = () => {
			const id = read(KEY_PRESET, DEFAULT_PRESET)
			return PRESET_BY_ID.has(id) ? id : DEFAULT_PRESET
		}
		const activeCodeFontId = () => {
			const id = read(KEY_FONT, 'default')
			return CODE_FONTS.some((choice) => choice.id === id) ? id : 'default'
		}
		const activeUiFontId = () => {
			const id = read(KEY_UI_FONT, 'default')
			return UI_FONTS.some((choice) => choice.id === id) ? id : 'default'
		}

		const notify = () => window.dispatchEvent(new Event(EVENT))

		/**
		 * A preset's anchors with the user's overrides applied. Only background,
		 * foreground and accent are overridable; the semantic families keep the
		 * preset's own values so a retint never destroys diff/error semantics.
		 */
		const effectiveSources = (preset, custom) => {
			const sources = { ...preset.sources }
			if (custom.accent && HEX.test(custom.accent)) {
				sources[ACCENT_FAMILY] = { light: custom.accent, dark: custom.accent }
			}
			if (custom.lightBg && HEX.test(custom.lightBg)) sources.lightBg = custom.lightBg
			if (custom.lightFg && HEX.test(custom.lightFg)) sources.lightFg = custom.lightFg
			if (custom.darkBg && HEX.test(custom.darkBg)) sources.darkBg = custom.darkBg
			if (custom.darkFg && HEX.test(custom.darkFg)) sources.darkFg = custom.darkFg
			return sources
		}

		const tokenCache = new Map()
		const tokensFor = (preset, custom) => {
			const key = preset.id + '|' + JSON.stringify(custom)
			const hit = tokenCache.get(key)
			if (hit) return hit
			const tokens = buildTokens(effectiveSources(preset, custom))
			tokenCache.set(key, tokens)
			return tokens
		}

		/** The two contrast readings the custom controls surface as live feedback. */
		const contrastReadout = (sources) => {
			const tokens = buildTokens(sources)
			const at = (stop, mode) => tokens['--dsw-static-neutral-bluish-' + String(stop).padStart(2, '0')][mode]
			return {
				light: contrast(at(1000, 'light'), at(0, 'light')),
				dark: contrast(at(50, 'dark'), at(950, 'dark')),
			}
		}

		// ─────────────────────────────── UI primitives ───────────────────────────────

		const SPACE = 8

		// Every surface, radius, border and shadow below comes from the official design
		// platform, so this page follows the host theme in both light and dark instead
		// of carrying its own palette.
		const groupStyle = {
			border: '1px solid var(--dsw-alias-settings-card-stroke, var(--dsw-alias-border-l2))',
			borderRadius: 'var(--dsw-radius-md)',
			background: 'var(--dsw-alias-settings-card-fill, var(--dsw-alias-bg-layer-1))',
		}
		const headStyle = {
			display: 'flex', alignItems: 'center', justifyContent: 'space-between',
			gap: SPACE * 2, padding: '12px 16px',
		}
		const rowStyle = {
			display: 'flex', alignItems: 'center', justifyContent: 'space-between',
			gap: '8px 16px', padding: '10px 16px', minHeight: 44, flexWrap: 'wrap',
			borderTop: '1px solid var(--dsw-alias-border-l2)',
		}
		const footStyle = {
			display: 'flex', alignItems: 'center', justifyContent: 'space-between',
			gap: SPACE * 1.5, padding: '10px 16px', flexWrap: 'wrap',
			borderTop: '1px solid var(--dsw-alias-border-l2)',
		}
		const titleStyle = { margin: 0, fontSize: 14, fontWeight: 600, color: 'var(--dsw-alias-label-primary)' }
		const subStyle = { marginTop: 2, fontSize: 12.5, color: 'var(--dsw-alias-label-tertiary)' }
		const labelStyle = { fontSize: 13.5, color: 'var(--dsw-alias-label-primary)', flex: 'none' }
		const ctrlStyle = { display: 'flex', alignItems: 'center', gap: SPACE, flexWrap: 'wrap', justifyContent: 'flex-end', marginLeft: 'auto' }
		// A fixed stack on purpose: the settings panel must not reflow when the CODE
		// font changes, or the whole page visibly jumps on every font switch.
		const UI_MONO = 'ui-monospace, SFMono-Regular, Menlo, Monaco, monospace'
		const hexStyle = { fontFamily: UI_MONO, fontSize: 12, color: 'var(--dsw-alias-label-secondary)' }
		const slashStyle = { color: 'var(--dsw-alias-label-tertiary)', fontSize: 12 }
		const dropdownStyle = {
			display: 'inline-flex', alignItems: 'center', justifyContent: 'space-between', gap: SPACE * 1.5,
			minWidth: 0, padding: '5px 10px', border: '1px solid var(--dsw-alias-border-l2)',
			borderRadius: 'var(--dsw-radius-sm)', background: 'none', color: 'var(--dsw-alias-label-primary)',
			font: 'inherit', cursor: 'pointer',
		}
		const menuStyle = {
			position: 'absolute', right: 0, top: 'calc(100% + 4px)', zIndex: 30, minWidth: 224,
			maxHeight: 264, overflowY: 'auto', padding: 6,
			background: 'var(--dsw-alias-bg-layer-2)', border: '1px solid var(--dsw-alias-border-l3)',
			borderRadius: 'var(--dsw-radius-md)', boxShadow: 'var(--dsw-shadow-lv3)',
		}
		const menuItemStyle = (highlighted) => ({
			display: 'flex', alignItems: 'center', gap: SPACE, padding: '6px 8px',
			borderRadius: 'var(--dsw-radius-sm)', cursor: 'pointer',
			background: highlighted ? 'var(--dsw-alias-interactive-bg-hover)' : 'none',
		})
		const pairChipStyle = {
			display: 'inline-flex', width: 34, height: 22, flex: 'none',
			borderRadius: 'var(--dsw-radius-xs)', overflow: 'hidden',
			border: '1px solid var(--dsw-alias-border-l2)',
		}
		const aaStyle = {
			display: 'inline-flex', alignItems: 'center', justifyContent: 'center', flex: 'none',
			width: 22, height: 22, borderRadius: '50%', fontSize: 12, fontWeight: 700,
			color: 'var(--dsw-static-deepseek-500)', background: 'var(--dsw-alias-interactive-bg-hover)',
		}
		const focusRing = {
			outline: '2px solid var(--dsw-focus-ring-color, var(--dsw-alias-state-business-primary))',
			outlineOffset: 2,
		}

		const onFocusRing = (e) => Object.assign(e.currentTarget.style, focusRing)
		const onBlurRing = (e) => Object.assign(e.currentTarget.style, { outline: 'none' })

		function Switch({ checked, onChange, label }) {
			return h('button', {
				type: 'button',
				role: 'switch',
				'aria-checked': checked,
				'aria-label': label,
				onClick: () => onChange(!checked),
				onFocus: onFocusRing,
				onBlur: onBlurRing,
				style: {
					position: 'relative', width: 44, height: 24, flex: 'none', padding: 0, border: 0,
					borderRadius: 999, cursor: 'pointer',
					background: checked ? 'var(--dsw-alias-brand-primary)' : 'var(--dsw-alias-bg-multi-select)',
					transition: 'background 150ms ease',
				},
			}, h('span', {
				'aria-hidden': true,
				style: {
					position: 'absolute', top: 2, left: checked ? 22 : 2, width: 20, height: 20, borderRadius: '50%',
					background: 'var(--dsw-alias-label-primary-foreground)', transition: 'left 150ms ease',
				},
			}))
		}

		const swatchBox = {
			width: 26, height: 22, flex: 'none',
			border: '1px solid var(--dsw-alias-border-l2)', borderRadius: 'var(--dsw-radius-xs)',
		}

		/**
		 * A native color well — on macOS the system picker, keyboard reachable — or a
		 * plain swatch when the value is not editable. A disabled input still reads as a
		 * control the user ought to be able to press; a swatch reads as a value.
		 */
		function ColorControl({ label, value, onChange, readOnly }) {
			if (readOnly) {
				return h('span', { 'aria-hidden': true, style: { ...swatchBox, background: value } })
			}
			return h('input', {
				type: 'color',
				'aria-label': label,
				value,
				onChange: (e) => onChange(e.target.value),
				onFocus: onFocusRing,
				onBlur: onBlurRing,
				style: { ...swatchBox, padding: 0, background: 'none', cursor: 'pointer' },
			})
		}

		/** A preset's light and dark page colour side by side: the whole reading of a theme. */
		function pairChipOf(preset) {
			return h('span', { 'aria-hidden': true, style: pairChipStyle },
				h('span', { style: { flex: 1, background: preset.preview.lightBg } }),
				h('span', { style: { flex: 1, background: preset.preview.darkBg } }))
		}

		/**
		 * A secondary action, rendered as text rather than a bordered button. The panel
		 * already carries one bordered control per row; a second container in the footer
		 * competes with them for attention.
		 */
		function TextAction({ label, hint, disabled, onClick }) {
			const [hover, setHover] = React.useState(false)
			return h('button', {
				type: 'button', disabled, title: hint,
				onClick,
				onMouseEnter: () => setHover(true),
				onMouseLeave: () => setHover(false),
				onFocus: onFocusRing, onBlur: onBlurRing,
				style: {
					border: 0, padding: '4px 8px', margin: '-4px -8px',
					borderRadius: 'var(--dsw-radius-xs)', font: 'inherit', fontSize: 13,
					background: !disabled && hover ? 'var(--dsw-alias-interactive-bg-hover)' : 'none',
					color: disabled ? 'var(--dsw-alias-label-tertiary)' : 'var(--dsw-alias-label-secondary)',
					cursor: disabled ? 'default' : 'pointer',
				},
			}, label)
		}

		/**
		 * One listbox-style dropdown, owning its open state, outside-click dismissal and
		 * keyboard behaviour: ArrowDown/Up move, Enter selects, Esc closes and returns
		 * focus to the trigger. Tab closes without stealing the next focus stop.
		 */
		function Dropdown({ label, value, options, onSelect, disabled, trigger }) {
			const [open, setOpen] = React.useState(false)
			const [active, setActive] = React.useState(0)
			const wrapRef = React.useRef(null)
			const btnRef = React.useRef(null)

			React.useEffect(() => {
				if (!open) return undefined
				const onDocDown = (event) => {
					if (wrapRef.current && !wrapRef.current.contains(event.target)) setOpen(false)
				}
				document.addEventListener('mousedown', onDocDown)
				return () => document.removeEventListener('mousedown', onDocDown)
			}, [open])

			const close = (refocus) => {
				setOpen(false)
				if (refocus && btnRef.current) btnRef.current.focus()
			}
			const commit = (id) => {
				onSelect(id)
				close(true)
			}
			const onKeyDown = (event) => {
				if (!open) {
					if (event.key === 'ArrowDown' || event.key === 'Enter' || event.key === ' ') {
						event.preventDefault()
						const index = options.findIndex((option) => option.id === value)
						setActive(index < 0 ? 0 : index)
						setOpen(true)
					}
					return
				}
				if (event.key === 'Escape') {
					event.preventDefault()
					close(true)
					return
				}
				if (event.key === 'Tab') {
					setOpen(false)
					return
				}
				if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
					event.preventDefault()
					const step = event.key === 'ArrowDown' ? 1 : -1
					setActive((index) => (index + step + options.length) % options.length)
					return
				}
				if (event.key === 'Enter' || event.key === ' ') {
					event.preventDefault()
					const option = options[active]
					if (option) commit(option.id)
				}
			}

			return h('div', { ref: wrapRef, style: { position: 'relative', minWidth: 0 } },
				h('button', {
					type: 'button', ref: btnRef, disabled,
					'aria-haspopup': 'listbox', 'aria-expanded': open, 'aria-label': label,
					onClick: () => (open ? close(false) : setOpen(true)),
					onKeyDown, onFocus: onFocusRing, onBlur: onBlurRing,
					style: { ...dropdownStyle, cursor: disabled ? 'default' : 'pointer', opacity: disabled ? 0.5 : 1 },
				},
					trigger,
					h('span', { 'aria-hidden': true, style: { color: 'var(--dsw-alias-label-tertiary)', fontSize: 10 } }, open ? '▲' : '▼'),
				),
				open ? h('div', { role: 'listbox', 'aria-label': label, style: menuStyle },
					options.map((option, index) => h('div', {
						key: option.id,
						role: 'option',
						'aria-selected': option.id === value,
						onMouseEnter: () => setActive(index),
						onClick: () => commit(option.id),
						style: menuItemStyle(index === active || option.id === value),
					},
						option.swatch || null,
						h('span', { style: { flex: 1, fontSize: 13, color: 'var(--dsw-alias-label-primary)' } }, option.label),
						option.id === value
							? h('span', { 'aria-hidden': true, style: { color: 'var(--dsw-static-deepseek-500)', fontSize: 12 } }, '✓')
							: null,
					))) : null,
			)
		}

		function Section() {
			const [enabled, setEnabled] = React.useState(isEnabled)
			const [presetId, setPresetId] = React.useState(activePresetId)
			const [uiFontId, setUiFontId] = React.useState(activeUiFontId)
			const [fontId, setFontId] = React.useState(activeCodeFontId)
			const [custom, setCustom] = React.useState(customValues)

			const preset = PRESET_BY_ID.get(presetId) ?? PRESETS[0]
			const sources = effectiveSources(preset, custom)
			const ratios = contrastReadout(sources)
			const worst = Math.min(ratios.light, ratios.dark)
			const customised = Object.values(custom).some((value) => value !== null)
			const accentFollows = !(custom.accent && HEX.test(custom.accent))
			const effectiveAccent = accentFollows ? preset.sources[ACCENT_FAMILY].light : custom.accent
			const labelOf = (list, id) => (list.find((entry) => entry.id === id) ?? list[0]).label
			const uiFontLabel = labelOf(UI_FONTS, uiFontId)
			const codeFontLabel = labelOf(CODE_FONTS, fontId)

			const pick = (id) => {
				write(KEY_PRESET, id)
				setPresetId(id)
				notify()
			}
			const pickFont = (id) => {
				write(KEY_FONT, id)
				setFontId(id)
				notify()
			}
			const pickUiFont = (id) => {
				write(KEY_UI_FONT, id)
				setUiFontId(id)
				notify()
			}
			const toggle = (next) => {
				write(KEY_ENABLED, next ? '1' : '0')
				setEnabled(next)
				notify()
			}
			const setField = (field, value) => {
				write(KEY_CUSTOM[field], value)
				setCustom((prev) => ({ ...prev, [field]: value }))
				notify()
			}
			const resetCustom = () => {
				for (const key of Object.values(KEY_CUSTOM)) write(key, '')
				setCustom(Object.fromEntries(Object.keys(KEY_CUSTOM).map((field) => [field, null])))
				notify()
			}

			const presetOptions = PRESETS.map((entry) => ({
				id: entry.id,
				label: entry.label,
				swatch: pairChipOf(entry),
			}))
			const accentOptions = [
				{ id: 'follow', label: '跟随主题' },
				{ id: 'custom', label: '自定义' },
			]
			const uiFontOptions = UI_FONTS.map((entry) => ({ id: entry.id, label: entry.label }))
			const fontOptions = CODE_FONTS.map((entry) => ({ id: entry.id, label: entry.label }))

			return h('div', { style: { paddingBottom: SPACE * 3 } },
				h('div', { style: groupStyle },
					h('div', { style: headStyle },
						h('div', { style: { minWidth: 0 } },
							h('div', { style: titleStyle }, '视觉风格'),
							h('div', { style: subStyle }, '配色与字体'),
						),
						h(Switch, { checked: enabled, onChange: toggle, label: '启用主题' }),
					),

					enabled ? null : h('div', { style: { ...rowStyle, fontSize: 12.5, color: 'var(--dsw-alias-label-tertiary)' } },
						'主题已关闭，下面的设置暂不生效。'),

					h('div', { style: { opacity: enabled ? 1 : 0.55 } },
						h('div', { style: rowStyle },
							h('span', { style: labelStyle }, '主题'),
							h('span', { style: ctrlStyle },
								h(Dropdown, {
									label: '主题预设',
									value: presetId,
									options: presetOptions,
									onSelect: pick,
									disabled: !enabled,
									trigger: h('span', { style: { display: 'flex', alignItems: 'center', gap: SPACE } },
										h('span', { 'aria-hidden': true, style: aaStyle }, 'Aa'),
										h('span', { style: { fontSize: 13.5 } }, preset.label)),
								}),
							),
						),

						h('div', { style: rowStyle },
							h('span', { style: labelStyle }, '强调色'),
							h('span', { style: ctrlStyle },
								h(ColorControl, {
									label: '强调色',
									value: effectiveAccent,
									readOnly: !enabled || accentFollows,
									onChange: (value) => setField('accent', value),
								}),
								h('span', { style: hexStyle }, effectiveAccent.toUpperCase()),
								h(Dropdown, {
									label: '强调色来源',
									value: accentFollows ? 'follow' : 'custom',
									options: accentOptions,
									disabled: !enabled,
									onSelect: (id) => setField('accent', id === 'follow' ? '' : effectiveAccent),
									trigger: h('span', { style: { fontSize: 13 } }, accentFollows ? '跟随主题' : '自定义'),
								}),
							),
						),

						h('div', { style: rowStyle },
							h('span', { style: labelStyle }, '背景'),
							h('span', { style: ctrlStyle },
								h(ColorControl, { label: '浅色背景', value: sources.lightBg, readOnly: !enabled, onChange: (value) => setField('lightBg', value) }),
								h('span', { style: hexStyle }, sources.lightBg.toUpperCase()),
								h('span', { 'aria-hidden': true, style: slashStyle }, '/'),
								h(ColorControl, { label: '深色背景', value: sources.darkBg, readOnly: !enabled, onChange: (value) => setField('darkBg', value) }),
								h('span', { style: hexStyle }, sources.darkBg.toUpperCase()),
							),
						),

						h('div', { style: rowStyle },
							h('span', { style: labelStyle }, '前景'),
							h('span', { style: ctrlStyle },
								h(ColorControl, { label: '浅色前景', value: sources.lightFg, readOnly: !enabled, onChange: (value) => setField('lightFg', value) }),
								h('span', { style: hexStyle }, sources.lightFg.toUpperCase()),
								h('span', { 'aria-hidden': true, style: slashStyle }, '/'),
								h(ColorControl, { label: '深色前景', value: sources.darkFg, readOnly: !enabled, onChange: (value) => setField('darkFg', value) }),
								h('span', { style: hexStyle }, sources.darkFg.toUpperCase()),
							),
						),

						h('div', { style: rowStyle },
							h('span', { style: labelStyle }, '正文字体'),
							h('span', { style: ctrlStyle },
								h(Dropdown, {
									label: '正文字体',
									value: uiFontId,
									options: uiFontOptions,
									onSelect: pickUiFont,
									disabled: !enabled,
									trigger: h('span', { style: { fontSize: 13 } }, uiFontLabel),
								}),
							),
						),

						h('div', { style: rowStyle },
							h('span', { style: labelStyle }, '代码字体'),
							h('span', { style: ctrlStyle },
								h(Dropdown, {
									label: '代码字体',
									value: fontId,
									options: fontOptions,
									onSelect: pickFont,
									disabled: !enabled,
									trigger: h('span', { style: { fontSize: 13 } }, codeFontLabel),
								}),
							),
						),
					),

					h('div', { style: footStyle },
						h('span', { style: { display: 'flex', alignItems: 'center', gap: SPACE, flexWrap: 'wrap' } },
							h('span', { style: { fontSize: 12.5, color: 'var(--dsw-alias-label-tertiary)' } }, '正文对比度'),
							h('span', {
								role: 'status',
								style: {
									fontSize: 12, padding: '3px 9px', borderRadius: 999,
									border: '1px solid ' + (worst < 4.5 ? 'var(--dsw-alias-state-error-primary)' : 'var(--dsw-alias-border-l2)'),
									color: worst < 4.5 ? 'var(--dsw-alias-state-error-primary)' : 'var(--dsw-alias-label-secondary)',
								},
							}, '浅色 ' + ratios.light.toFixed(2) + ':1 · 深色 ' + ratios.dark.toFixed(2) + ':1'
								+ (worst < 4.5 ? ' · 低于 4.5:1' : ' · 达标')),
						),
						h(TextAction, {
							label: customised ? '清除自定义' : '未做自定义',
							hint: customised ? '只清除自定义色号，不改变已选预设' : '当前没有自定义色号',
							disabled: !customised,
							onClick: resetCustom,
						}),
					),
				),
			)
		}

		return {
			inject: ['theme', 'slots'],
			apply(ctx) {
				let disposeLayer = null
				let lastTokenKey = null

				/**
				 * The colour ramp goes through ctx.theme.overrideTokens — the sanctioned
				 * channel. It rewrites every token on body, so it is only worth doing when
				 * the palette itself changed.
				 */
				const syncTokens = () => {
					const key = (isEnabled() ? '1' : '0') + '|' + activePresetId() + '|' + JSON.stringify(customValues())
					if (key === lastTokenKey) return
					lastTokenKey = key
					if (disposeLayer) {
						disposeLayer()
						disposeLayer = null
					}
					if (!isEnabled()) return
					const preset = PRESET_BY_ID.get(activePresetId()) ?? PRESETS[0]
					disposeLayer = ctx.theme.overrideTokens(PACKAGE, tokensFor(preset, customValues()))
				}

				/**
				 * The code face is one variable, so it gets one stylesheet rule of our own
				 * instead of a theme republish. Rewriting a single rule costs one style
				 * recalc; republishing the theme re-renders the whole application, which is
				 * what made the page jump on every font change.
				 */
				const syncFont = () => {
					const existing = document.getElementById(FONT_STYLE_ID)
					if (!isEnabled()) {
						if (existing) existing.remove()
						return
					}
					const ui = UI_FONTS.find((entry) => entry.id === activeUiFontId()) ?? UI_FONTS[0]
					const code = CODE_FONTS.find((entry) => entry.id === activeCodeFontId()) ?? CODE_FONTS[0]
					const css = 'body{--dsw-font-family:' + ui.ui + ';--ds-font-family-code:' + code.code + '}'
					if (existing) {
						if (existing.textContent !== css) existing.textContent = css
						return
					}
					const tag = document.createElement('style')
					tag.id = FONT_STYLE_ID
					tag.dataset.plugin = PACKAGE
					tag.textContent = css
					document.head.appendChild(tag)
				}

				const sync = () => {
					syncTokens()
					syncFont()
				}

				sync()

				ctx.effect(() => {
					const onChanged = () => sync()
					window.addEventListener(EVENT, onChanged)
					return () => {
						window.removeEventListener(EVENT, onChanged)
						if (disposeLayer) {
							disposeLayer()
							disposeLayer = null
						}
						const tag = document.getElementById(FONT_STYLE_ID)
						if (tag) tag.remove()
					}
				}, 'codex-theme: token + code-face override')

				ctx.slots.inject('settings.section', () => ctx.slots.register({
					name: 'settings.section',
					id: 'codex-theme',
					order: 18,
					label: () => '主题',
				}, Section))
			},
		}
	},
})
`

const outPath = path.join(root, 'plugin', 'client.js')
fs.writeFileSync(outPath, client)
console.log(`wrote ${path.relative(root, outPath)}`)
console.log(`  package:   ${PACKAGE}`)
console.log(`  presets:   ${presets.length} (default ${generated.defaultPreset}), source anchors only`)
console.log(`  inlined:   ${MODULES.length} bytes of ramp + ladder code`)
console.log(`  tokens:    ${generated.report[0]?.tokens ?? '?'} per preset, derived at runtime`)
console.log(`  bytes:     ${client.length}`)
